# Generated by Django 4.2.11 on 2024-08-14 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='m_initial',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='m_initial',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='approvedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_intellectual_property', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='approvedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='disapprovedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='ipviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='mainauthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainauthorfirstname_intellectual_property', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.college'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile-default.svg', null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='intellectualproperty',
            name='author',
        ),
        migrations.AlterField(
            model_name='intellectualproperty',
            name='cover',
            field=models.ImageField(blank=True, default='Abtract Cover.svg', null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='intellectualproperty',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intellectualproperty',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_intellectual_property', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='intellectualproperty',
            name='tittle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.type')),
            ],
        ),
        migrations.CreateModel(
            name='CommenReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subtype'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='author',
            field=models.ManyToManyField(related_name='authored_intellectual_property', to=settings.AUTH_USER_MODEL),
        ),
    ]
