# Generated by Django 4.2.11 on 2024-10-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_coordinator_dob_remove_coordinator_m_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intellectualproperty',
            name='tittle',
            field=models.CharField(max_length=100),
        ),
    ]
