# Generated by Django 4.2.11 on 2024-11-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_intellectualproperty_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intellectualproperty',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
